services:
  db:
    container_name: linker-db
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - linker_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - linker_backend

volumes:
  linker_db_data:

networks:
  linker_backend:
    external: true